name: Deploy pages
on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --force
      - name: Build
        run: npm run build

      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.aliyun_oss_accessKey_id }}
          key-secret: ${{ secrets.aliyun_oss_accessKey_secret }}
          region: ${{ secrets.aliyun_oss_region }}
          bucket: ${{ secrets.aliyun_oss_bucket_name }}
          assets: |
            dist/**:/
